blank_issues_enabled: false
contact_links:
  - name: Theme Documentation 主题文档
    url: https://hugoloveit.com/categories/documentation/
    about: Please read the documentation carefully. 请先仔细阅读主题文档.
